#!/usr/bin/env bash
set -e

command=$1
shift

compose_base() {
    set -x
    docker-compose "$@"
}

build() {
    compose_base build "$@"
}

run() {
    compose_base run ng go run "$@"
}

bash() {
    compose_base run ng bash
}

go() {
    compose_base run ng go "$@"
}

case $command in
build)
    build "$@"
    ;;
fresh_build)
    build --no-cache
    ;;
run)
    run "$@"
    ;;
bash)
    bash
    ;;
go)
    go "$@"
    ;;
*)
    echo "Error: command not found: $command"
    exit 1
    ;;
esac
